### ISSUE TITLE
Close on click outside box

### ISSUE THREAD

**Issue by softwaretech** [wenzhixin/multiple-select#213] opened 2015-06-24 22:21 UTC
I would love to have some type of options that allows me to close the dropdown when clicking outside.  In other words, if the dropdown list is showing and I click somewhere else besides a radio button or checkbox, then allow the dropdown to close.

**Comment by vlad00777** [comment] 2015-07-06 09:03
I have some problem too.

**Comment by wenzhixin** [comment] 2015-11-24 11:35
Fixed in the latest version.

**Closed by wenzhixin** 2015-11-24 11:35 UTC

**Comment by PlippiePlop** [comment] 2015-12-10 12:27
Closing when clicking outside the box works. However if you tab or click directly to another input, select or form button it does not close. Please fix.

**Comment by wenzhixin** [comment] 2015-12-10 12:32
Can you provide a jsfiddle base on the example: https://github.com/wenzhixin/multiple-select/issues/255?

**Comment by PlippiePlop** [comment] 2015-12-10 12:51
Ok seems the clicking on other form elements works but tabbing is not.
https://jsfiddle.net/zthab5mn/

**Comment by wenzhixin** [comment] 2015-12-10 15:15
I think this is not a bug because tabbing is an iframe.
![1](https://cloud.githubusercontent.com/assets/2117018/11719057/e8eebcb0-9f93-11e5-9f2f-c53d3b680799.png)

**Comment by PlippiePlop** [comment] 2015-12-10 15:39
If you have tab indexes on input fields (user friendlybess, disabbled people etc) you can tab from input to input. Normal selects will close and the focus is on the next field. You can tab through the options en then it will go to next field but not close multiselect.

**Comment by wenzhixin** [comment] 2015-12-10 15:42
Do you mean use the `tab` key to the next input when open this dropdown? in this case, you need to use `esc` to close the dropdown first.

**Comment by PlippiePlop** [comment] 2015-12-10 15:45
Normal behavior is tab to select: Use arrow to select options or enter to select item or tab to jump out of select: Try it here:
https://formidablepro.com/demos/job-listings/

**Comment by wenzhixin** [comment] 2015-12-10 15:55
Maybe we can add `enter` to close dropdown(the same with `esc`), you can open a new feature issue.
