### ISSUE TITLE
triggers multiple change events after changing a value

### ISSUE THREAD

**Issue by prabuFinetech** [wenzhixin/multiple-select#270] opened 2016-01-12 09:04 UTC
hi my trying out this plugin for my project but its triggers multiple change events after changing a value

**Comment by dsoriano** [comment] 2016-01-12 10:28
I have the problem too. The select trigger two "change" event. I think the problem is coming from the update() function : 

            // set selects to select
            this.$el.val(this.getSelects()).trigger('change');

            // add selected class to selected li
            this.$drop.find('li').removeClass('selected');
            this.$drop.find('input:checked').each(function () {
                $(this).parents('li').first().addClass('selected');
            });

            // trigger <select> change event
            if (!isInit) {
                this.$el.trigger('change');
            }

There is two "change" event triggered. For ajax call on this event this is a problem. Thanks for your help.

**Comment by wenzhixin** [comment] 2019-04-25 13:02
Fixed in the latest version.

**Closed by wenzhixin** 2019-04-25 13:02 UTC
