### ISSUE TITLE
when filter character ک arabic in search box no result found

### ISSUE THREAD

**Issue by webtinax** [wenzhixin/multiple-select#581] opened 2021-12-04 12:04 UTC
hi when i serach in select box a word with char (ک) results not found!

please help me!

**Comment by webtinax** [comment] 2022-06-29 21:53
????

**Comment by ghiscoding** [comment] 2024-01-12 21:52
probably caused by this code, you need to add assigned unicode for it

https://github.com/wenzhixin/multiple-select/blob/52ece8d752814caf3808d5e2a60a362a5115f3f5/src/utils/index.js#L18-L112

**Comment by wenzhixin** [comment] 2024-01-13 09:41
Fixed in the latest version: https://multiple-select-live.wenzhixin.net.cn/code/wenzhixin/16925
![image](https://github.com/wenzhixin/multiple-select/assets/2117018/33c02538-c832-49b5-ac84-c48a060ba75c)

**Closed by wenzhixin** 2024-01-13 09:41 UTC
