### ISSUE TITLE
oprgroups and countSelected problem

### ISSUE THREAD

**Issue by max-mykhailenko** [wenzhixin/multiple-select#67] opened 2014-05-05 19:48 UTC
minumimCountSelected and countSelected don't work when use optgroups

**Comment by andreasringdal** [comment] 2016-01-15 07:51
Shouldn't this be listed as bug and not enhancement?

**Comment by eoutvik** [comment] 2016-01-15 10:53
Bug caused by getSelect('text') only returns array of optgroups when in use (line 476).
Workaround: 
```
$('select').multipleSelect({
  displayValues: true,
  minimumCountSelected: 0
})
```
This will only display number of selected elements (1 of 18 selected), not their text label.

**Comment by athill** [comment] 2016-05-04 16:41
Can countSelected be modified to accept a function that returns a string? I'd like to handle my own display.

**Comment by fixwa** [comment] 2017-05-23 17:15
I'm also having this problem. 
Any workaround or ideas?

**Comment by BlakeTsao** [comment] 2017-06-03 02:39
modify the code in "update:" part
we can add the code to get the real countSelected number in oprgroups:
`
var selects = this.options.displayValues ? this.getSelects() : this.getSelects('getSelects');
var number = selects.length;
`
so, just modify the program logic of information presented

**Comment by developerNothing** [comment] 2017-09-11 04:52
@BlakeTsao : What is the value of "de_selects"?

**Comment by BlakeTsao** [comment] 2017-09-11 05:44
@developerNothing 
`var number = all_selects.length;`
I think it's a typo.

**Comment by ssttm169** [comment] 2018-01-31 02:55
@eoutvik  You did a job, I have fixed my problem, thanks a lot.

**Comment by wenzhixin** [comment] 2019-08-13 15:37
Fixed in the latest version.

* [minimumCountSelected](http://multiple-select.wenzhixin.net.cn/documentation/#options-minimumcountselected): [example](http://multiple-select.wenzhixin.net.cn/examples/#minimum-count-selected.html)
* [formatCountSelected](http://multiple-select.wenzhixin.net.cn/documentation/#localizations-formatcountselected): [example](http://multiple-select.wenzhixin.net.cn/examples/#i18n.html)

**Closed by wenzhixin** 2019-08-13 15:37 UTC
Labels: feature
